// The human round-trip contract: writes and parses 03-script/dub-script.md (Nils writes the English there).
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { ensureDayDirs, fmtTime, loadConfig, log, readJson, sha256, warn, writeJson } from './config'
import { isDone, loadState, markDone } from './state'
import type { Config, ScriptEntry, ScriptFile, Segment, SegmentsFile } from './types'

export const KNOWN_FLAGS = ['music', 'silence', 'keep-de', 'skip', 'tempo=1'] as const

function header(seg: Segment, cfg: Config): string {
  const target = Math.round(seg.spokenSec * cfg.script.wordsPerSec)
  const max = Math.round(seg.slotSec * cfg.script.wordsPerSec * cfg.fit.atempoCap)
  const auto: string[] = []
  if (seg.auto.music) auto.push('auto:music')
  if (seg.auto.suspect) auto.push('auto:suspect')
  return `## ${seg.id} · ${fmtTime(seg.start)} → ${fmtTime(seg.end)} · spoken ${seg.spokenSec.toFixed(1)}s · slot ${seg.slotSec.toFixed(1)}s · DE ${seg.deWords} words · EN target ~${target} · max ${max}${auto.length ? ' · ' + auto.join(' ') : ''}`
}

export interface ParsedBlock {
  id: string
  en: string
  flags: string[]
  note: string
}

/** Line-anchored parser: ## <id> … / DE: … / EN: … (multi-line) / FLAGS: … / NOTE: … */
export function parseScriptMd(md: string): { blocks: ParsedBlock[]; errors: string[] } {
  const lines = md.split('\n')
  const blocks: ParsedBlock[] = []
  const errors: string[] = []
  let cur: ParsedBlock | null = null
  let field: 'en' | 'note' | null = null
  let orphanZone = false
  lines.forEach((line, i) => {
    const h = line.match(/^##\s+(s\d{3})\b/)
    if (h) {
      if (cur) blocks.push(cur)
      cur = { id: h[1], en: '', flags: [], note: '' }
      field = null
      orphanZone = false
      return
    }
    if (/^##\s+orphaned\b/i.test(line)) {
      if (cur) blocks.push(cur)
      cur = null
      orphanZone = true
      return
    }
    if (orphanZone || !cur) return
    const de = line.match(/^DE:\s?(.*)$/)
    if (de) {
      field = null
      return
    }
    const en = line.match(/^EN:\s?(.*)$/)
    if (en) {
      cur.en = en[1].trim()
      field = 'en'
      return
    }
    const fl = line.match(/^FLAGS:\s?(.*)$/)
    if (fl) {
      field = null
      const toks = fl[1].split(/[\s,]+/).map((t) => t.trim()).filter(Boolean)
      for (const t of toks) {
        if ((KNOWN_FLAGS as readonly string[]).includes(t) || /^seed=\d+$/.test(t)) cur.flags.push(t)
        else errors.push(`line ${i + 1}: unknown flag "${t}" in ${cur.id}`)
      }
      return
    }
    const nt = line.match(/^NOTE:\s?(.*)$/)
    if (nt) {
      cur.note = nt[1].trim()
      field = 'note'
      return
    }
    if (field === 'en' && line.trim() && !line.startsWith('<!--')) cur.en = `${cur.en} ${line.trim()}`.trim()
    else if (field === 'note' && line.trim()) cur.note = `${cur.note} ${line.trim()}`.trim()
  })
  if (cur) blocks.push(cur)
  for (const b of blocks) b.en = b.en.replace(/\s+/g, ' ').trim()
  return { blocks, errors }
}

export function renderScriptMd(segs: SegmentsFile, cfg: Config, existing: Map<string, ParsedBlock>, title: string): string {
  const out: string[] = []
  out.push(`# Tag ${String(segs.day).padStart(2, '0')} · ${title} · dub script`)
  out.push(`<!-- generated ${new Date().toISOString()} · edit only EN / FLAGS / NOTE lines — header and DE lines are regenerated by \`script --refresh\` -->`)
  out.push(`<!-- wordsPerSec ${cfg.script.wordsPerSec} · atempo cap ${cfg.fit.atempoCap} · target = spoken×wps · max = slot×wps×cap -->`)
  out.push(`<!-- FLAGS: music | silence | keep-de | skip | tempo=1 | seed=<int> -->`)
  out.push('')
  const seen = new Set<string>()
  for (const seg of segs.segments) {
    const prev = existing.get(seg.id)
    seen.add(seg.id)
    out.push(header(seg, cfg))
    out.push(`DE: ${seg.de}`)
    out.push(`EN: ${prev?.en ?? ''}`)
    const flags = prev?.flags?.length ? prev.flags.join(' ') : ''
    out.push(`FLAGS: ${flags}`)
    if (prev?.note) out.push(`NOTE: ${prev.note}`)
    out.push('')
  }
  const orphans = [...existing.values()].filter((b) => !seen.has(b.id) && (b.en || b.flags.length || b.note))
  if (orphans.length) {
    out.push('## orphaned')
    out.push('<!-- segment ids that no longer exist after re-transcription; kept so no written English is lost -->')
    for (const o of orphans) {
      out.push(`- ${o.id} · EN: ${o.en}${o.flags.length ? ` · FLAGS: ${o.flags.join(' ')}` : ''}${o.note ? ` · NOTE: ${o.note}` : ''}`)
    }
    out.push('')
  }
  return out.join('\n')
}

function dayTitle(day: number): string {
  try {
    const src = readFileSync(new URL('../../data/rhythmusfundament-days.ts', import.meta.url), 'utf8')
    const re = new RegExp(`number:\\s*${day},[\\s\\S]{0,200}?title:\\s*'([^']+)'`)
    return src.match(re)?.[1] ?? ''
  } catch {
    return ''
  }
}

export function writeScript(day: number, opts: { force?: boolean; refresh?: boolean } = {}): void {
  const p = ensureDayDirs(day)
  const cfg = loadConfig()
  if (!existsSync(p.segments)) throw new Error(`script: ${p.segments} missing; run transcribe first`)
  const segs = readJson<SegmentsFile>(p.segments)
  const exists = existsSync(p.scriptMd)
  if (exists && !opts.force && !opts.refresh) {
    log(`script: ${p.scriptMd} already exists (use --refresh to update headers, --force to overwrite)`)
    return
  }
  const existing = new Map<string, ParsedBlock>()
  if (exists) {
    const { blocks, errors } = parseScriptMd(readFileSync(p.scriptMd, 'utf8'))
    for (const e of errors) warn(e)
    if (!opts.force) for (const b of blocks) existing.set(b.id, b)
  }
  writeFileSync(p.scriptMd, renderScriptMd(segs, cfg, existing, dayTitle(day)))
  log(`script: wrote ${p.scriptMd} (${segs.segments.length} segments${exists ? `, kept ${existing.size} existing EN blocks` : ''})`)
}

const LINT_PATTERNS: [RegExp, string][] = [
  [/\d/, 'contains digits — write numbers as words'],
  [/[&%@#]/, 'contains a symbol the TTS may skip — write it out'],
  [/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u, 'contains emoji'],
]

export function parseScript(day: number, opts: { lint?: boolean } = {}): ScriptFile {
  const p = ensureDayDirs(day)
  const cfg = loadConfig()
  if (!existsSync(p.scriptMd)) throw new Error(`script: ${p.scriptMd} missing; run "script --day ${day}" first`)
  if (!existsSync(p.segments)) throw new Error(`script: ${p.segments} missing`)
  const segs = readJson<SegmentsFile>(p.segments)
  const { blocks, errors } = parseScriptMd(readFileSync(p.scriptMd, 'utf8'))
  for (const e of errors) warn(e)
  const byId = new Map(blocks.map((b) => [b.id, b]))
  const entries: ScriptEntry[] = []
  let missing = 0
  for (const seg of segs.segments) {
    const b = byId.get(seg.id) ?? { id: seg.id, en: '', flags: [], note: '' }
    const seedFlag = b.flags.find((f) => f.startsWith('seed='))
    const enWords = b.en ? b.en.split(/\s+/).filter(Boolean).length : 0
    const skip = b.flags.includes('skip') || b.flags.includes('keep-de')
    if (!b.en && !skip) missing++
    if (opts.lint && b.en) {
      for (const [re, msg] of LINT_PATTERNS) if (re.test(b.en)) warn(`${seg.id}: ${msg}`)
      const budget = Math.round(seg.slotSec * cfg.script.wordsPerSec * cfg.fit.atempoCap)
      if (enWords > budget) warn(`${seg.id}: ${enWords} EN words exceed the ${budget}-word slot budget — expect overflow`)
      if (b.en.length > 600) warn(`${seg.id}: ${b.en.length} characters — long lines chunk and may drift in tone`)
    }
    entries.push({
      id: seg.id,
      en: b.en,
      flags: b.flags,
      note: b.note,
      enWords,
      enHash: sha256(b.en),
      ...(seedFlag ? { seed: Number(seedFlag.split('=')[1]) } : {}),
    })
  }
  const orphaned = blocks.filter((b) => !segs.segments.some((s) => s.id === b.id)).map((b) => b.id)
  const file: ScriptFile = { day, parsedAt: new Date().toISOString(), entries, orphaned }
  writeJson(p.scriptJson, file)
  const state = loadState(day)
  markDone(state, 'script', sha256(entries.map((e) => `${e.id}:${e.enHash}:${e.flags.join(',')}`).join('|')))
  const ready = entries.filter((e) => e.en || e.flags.includes('skip') || e.flags.includes('keep-de')).length
  log(`script: parsed ${entries.length} segments, ${ready} ready, ${missing} missing EN${orphaned.length ? `, ${orphaned.length} orphaned` : ''}`)
  return file
}

export function scriptReady(day: number): boolean {
  const p = ensureDayDirs(day)
  if (!existsSync(p.scriptJson)) return false
  const s = readJson<ScriptFile>(p.scriptJson)
  return s.entries.every((e) => e.en || e.flags.includes('skip') || e.flags.includes('keep-de'))
}
